"use client"
import { SessionProvider } from 'next-auth/react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ProviderWrapper({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionProvider>
        {children}  {/* Our Entire app -> that means our entire app has access to NextAuth*/}
    </SessionProvider>
  )
}
